"""many to many with user via emergency response

Revision ID: 54e6926f1c7b
Revises: 4ccbb4177d2b
Create Date: 2025-01-28 09:26:56.892816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e6926f1c7b'
down_revision = '4ccbb4177d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('assistance_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], name=op.f('fk_emergency_responses_response_id_responses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emergency_responses_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_responses')
    # ### end Alembic commands ###
